QLVinpearl_63130803/Areas/Admin/Controllers/KHACHHANGs_63130803Controller.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLVinpearl_63130803.Models;

namespace QLVinpearl_63130803.Areas.Admin.Controllers
{
    public class KHACHHANGs_63130803Controller : Controller
    {
        private QLVinpearl_63130803Entities db = new QLVinpearl_63130803Entities();
        // Kiểm tra quyền của nhân viên
        public bool CheckPermission(string maChucNang)
        {
            if (Session["maLNV"] == null) Response.Redirect("~/Admin/Login_63130803/Index");
            var userSession = Session["maLNV"].ToString();
            var count = db.PHANQUYENs.Count(m => m.maLoaiNV == userSession && m.maChucNang == maChucNang);
            if (count == 0)
            {
                return false;
            }
            return true;
        }
        // GET: Admin/KHACHHANGs_63130803
        public ActionResult Index()
        {
            //return View(db.KHACHHANGs.ToList());
            if (CheckPermission("CN01") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            return View(db.KHACHHANGs.ToList());
        }

        // GET: Admin/KHACHHANGs_63130803/Details/5
        public ActionResult Details(string id)
        {
            if (CheckPermission("CN01") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHACHHANG kHACHHANG = db.KHACHHANGs.Find(id);
            if (kHACHHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHACHHANG);
        }

        // GET: Admin/KHACHHANGs_63130803/Create
        string LayMaKH()
        {
            // query lấy mã cuối cùng trong bảng và parse sang số
            var maMax = db.KHACHHANGs.ToList().Select(n => n.maKH).Max();
            int maKH = int.Parse(maMax.Substring(2)) + 1;
            // mã kh: KH000000 => 6 số
            string KH = maKH.ToString().PadLeft(6, '0');
            return "KH" + KH;
        }
        public ActionResult Create()
        {
            //return View();
            if (CheckPermission("CN02") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            ViewBag.MaKH = LayMaKH();
            return View();
        }

        // POST: Admin/KHACHHANGs_63130803/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "maKH,hoTenKH,SDT,diaChi,ngaySinh,gioiTinh,email,matKhau,anh,ResetPasswordCode,ResetPasswordCodeExpiration")] KHACHHANG kHACHHANG)
        {
            var imgUser = Request.Files["Avatar"];
            string postedFileName = System.IO.Path.GetFileName(imgUser.FileName);
            var path = Server.MapPath("/Content/img/Avatar" + postedFileName);
            imgUser.SaveAs(path);
            if (ModelState.IsValid)
            {
                kHACHHANG.maKH = LayMaKH();
                kHACHHANG.anh = postedFileName;
                kHACHHANG.ResetPasswordCode = null;
                kHACHHANG.ResetPasswordCodeExpiration = null;
                db.KHACHHANGs.Add(kHACHHANG);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kHACHHANG);
        }

        // GET: Admin/KHACHHANGs_63130803/Edit/5
        public ActionResult Edit(string id)
        {
            if (CheckPermission("CN03") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHACHHANG kHACHHANG = db.KHACHHANGs.Find(id);
            if (kHACHHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHACHHANG);
        }

        // POST: Admin/KHACHHANGs_63130803/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "maKH,hoTenKH,SDT,diaChi,ngaySinh,gioiTinh,email,matKhau,anh,ResetPasswordCode,ResetPasswordCodeExpiration")] KHACHHANG kHACHHANG)
        {
            var imgUser = Request.Files["Avatar"];
            try
            {
                string postedFileName = System.IO.Path.GetFileName(imgUser.FileName);
                var path = Server.MapPath("/Content/img/Avatar" + postedFileName);
                imgUser.SaveAs(path);
            }
            catch { }
            if (ModelState.IsValid)
            {
                db.Entry(kHACHHANG).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(kHACHHANG);
        }

        // GET: Admin/KHACHHANGs_63130803/Delete/5
        public ActionResult Delete(string id)
        {
            if (CheckPermission("CN04") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            KHACHHANG kHACHHANG = db.KHACHHANGs.Find(id);
            if (kHACHHANG == null)
            {
                return HttpNotFound();
            }
            return View(kHACHHANG);
        }

        // POST: Admin/KHACHHANGs_63130803/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            KHACHHANG kHACHHANG = db.KHACHHANGs.Find(id);
            db.KHACHHANGs.Remove(kHACHHANG);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLVinpearl_63130803/Areas/Admin/Views/KHACHHANGs_63130803/Create.cshtml
@model QLVinpearl_63130803.Models.KHACHHANG

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm("Create", "KHACHHANGs_63130803", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row justify-content-center align-items-center h-100">
                <div class="col-12 col-lg-9 col-xl-7">
                    <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                        <div class="card-body p-4 p-md-5">
                            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Thêm mới khách hàng</h3>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        <label class="form-label fw-bold">Họ Tên</label>
                                        @Html.EditorFor(model => model.hoTenKH, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.hoTenKH, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        <label class="form-label fw-bold">Số Điện Thoại</label>
                                        @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 d-flex align-items-center">
                                    <div class="form-outline datepicker w-100">
                                        <label class="form-label fw-bold">Địa Chỉ</label>
                                        @Html.TextAreaFor(model => model.diaChi, new { @class = "form-control form-control-lg" })
                                        @Html.ValidationMessageFor(model => model.diaChi, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline datepicker w-100">
                                        <label class="form-label fw-bold">Ngày Sinh</label>
                                        @Html.EditorFor(model => model.ngaySinh, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.ngaySinh, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 pb-2">
                                    <label class="form-label fw-bold mt-4">Giới Tính</label>
                                    <div class="form-outline datepicker w-100 ">
                                        <div class="form-check form-check-inline">
                                            <label class="form-check-label" for="femaleGender">Nam</label>
                                            @Html.RadioButtonFor(model => model.gioiTinh, "True", new { @class = "form-check-input", @checked = "checked" })
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <label class="form-check-label" for="maleGender">Nữ</label>
                                            @Html.RadioButtonFor(model => model.gioiTinh, "False", new { @class = "form-check-input" })
                                        </div>
                                        <br />
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4 pb-2">
                                    <div class="form-outline datepicker w-100">
                                        <label class="form-label fw-bold">Email</label>
                                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 d-flex align-items-center">
                                    <div class="form-outline datepicker w-100">
                                        <label class="form-label fw-bold">Mật Khẩu</label>
                                        @Html.EditorFor(model => model.matKhau, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.matKhau, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline datepicker w-100">
                                        <label class="form-label fw-bold mt-3">Ảnh</label>
                                        <input type="file" name="Avatar" accept="image/*" required />
                                        @Html.ValidationMessageFor(model => model.anh, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div style="width: 100%">
                                <div class="m-auto">
                                    <input class="btn btn-primary btn-lg" type="submit" value="Thêm" />
                                    @Html.ActionLink("Quay Về", "Index", null, new { @class = "btn btn-primary btn-lg" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

QLVinpearl_63130803/Areas/Admin/Views/KHACHHANGs_63130803/Delete.cshtml
@model QLVinpearl_63130803.Models.KHACHHANG

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="container">
    <h3>Bạn có chắc chắn muốn xoá người dùng này không?</h3>
    <br />
    <p><span class="fw-bold">Họ và tên</span><br /><span>@Html.DisplayFor(model => model.hoTenKH)</span></p>
    <p><span class="fw-bold">Số điện thoại</span><br /><span>@Html.DisplayFor(model => model.SDT)</span></p>
    <p><span class="fw-bold">Email</span><br /><span>@Html.DisplayFor(model => model.email)</span></p>
    @using (Html.BeginForm("Delete", "KHACHHANGs_63130803", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="m-auto">
            <input class="btn btn-primary btn-lg" type="submit" value="Xoá" />
            @Html.ActionLink("Quay Về", "Index", null, new { @class = "btn btn-primary btn-lg" })
        </div>
    }
</div>

QLVinpearl_63130803/Areas/Admin/Views/KHACHHANGs_63130803/Details.cshtml
@model QLVinpearl_63130803.Models.KHACHHANG

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>KHACHHANG</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.hoTenKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.hoTenKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.diaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.diaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ngaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ngaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.matKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.matKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.anh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.anh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResetPasswordCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResetPasswordCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResetPasswordCodeExpiration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResetPasswordCodeExpiration)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.maKH }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QLVinpearl_63130803/Areas/Admin/Views/KHACHHANGs_63130803/Edit.cshtml
@model QLVinpearl_63130803.Models.KHACHHANG

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
		$(function () {
			var fileupload = $("#Avatar");
			var image = $("#FileUpload");
			image.click(function () {
				fileupload.click();
			});
			fileupload.change(function () {
				var fileName = $(this).val().split('\\')[$(this).val().split('\\').length - 1];
				document.getElementById("anh").value = fileName;
			});
		});
    </script>
}
@using (Html.BeginForm("Edit", "KHACHHANGs_63130803", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row justify-content-center align-items-center h-100">
                <div class="col-12 col-lg-9 col-xl-7">
                    <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                        <div class="card-body p-4 p-md-5">
                            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Sửa thông tin khách hàng</h3>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.maKH)
                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        <label class="form-label fw-bold">Họ Tên</label>
                                        @Html.EditorFor(model => model.hoTenKH, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.hoTenKH, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        <label class="form-label fw-bold">Số Điện Thoại</label>
                                        @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 d-flex align-items-center">
                                    <div class="form-outline datepicker w-100">
                                        <label class="form-label fw-bold">Địa Chỉ</label>
                                        @Html.TextAreaFor(model => model.diaChi, new { @class = "form-control form-control-lg" })
                                        @Html.ValidationMessageFor(model => model.diaChi, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline datepicker w-100">
                                        <label class="form-label fw-bold">Ngày Sinh</label>
                                        @*@Html.EditorFor(model => model.ngaySinh, new { htmlAttributes = new { @class = "form-control form-control-lg" } })*@
                                        @Html.TextBoxFor(model => model.ngaySinh, "{0:MM/dd/yyyy}", new { @class = "form-control form-control-lg datepicker" })
                                        @Html.ValidationMessageFor(model => model.ngaySinh, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 pb-2">
                                    <label class="form-label fw-bold mt-4">Giới Tính</label>
                                    <div class="form-outline datepicker w-100 ">
                                        <div class="form-check form-check-inline">
                                            <label class="form-check-label" for="femaleGender">Nam</label>
                                            @Html.RadioButtonFor(model => model.gioiTinh, "True", new { @class = "form-check-input", @checked = "checked" })
                                        </div>
                                        <div class="form-check form-check-inline">
                                            <label class="form-check-label" for="maleGender">Nữ</label>
                                            @Html.RadioButtonFor(model => model.gioiTinh, "False", new { @class = "form-check-input" })
                                        </div>
                                        <br />
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4 pb-2">
                                    <div class="form-outline datepicker w-100">
                                        <label class="form-label fw-bold">Email</label>
                                        @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 d-flex align-items-center">
                                    <div class="form-outline datepicker w-100">
                                        <label class="form-label fw-bold">Mật Khẩu</label>
                                        @Html.EditorFor(model => model.matKhau, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.matKhau, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-outline datepicker w-100">
                                        <label class="form-label fw-bold">Ảnh</label>
                                        <div style="display:flex ">
                                            <input class="form-control form-control-lg" type="file" name="Avatar" id="Avatar" style="margin-right: 5px;" />
                                            @Html.EditorFor(model => model.anh)
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div style="width: 100%;">
                                <div class="m-auto">
                                    <input class="btn btn-primary btn-lg" type="submit" value="Cập nhật" />
                                    @Html.ActionLink("Quay Về", "Index", null, new { @class = "btn btn-primary btn-lg" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

QLVinpearl_63130803/Areas/Admin/Views/KHACHHANGs_63130803/Index.cshtml
@model IEnumerable<QLVinpearl_63130803.Models.KHACHHANG>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    string gtinh = "";
}
<main>
    <div class="container-fluid px-4">
        <br />
        <h2>Danh sách khách hàng</h2>

        <div class="my-3 flex">
            @Html.ActionLink("Thêm mới", "Create", null, new { @class = "btn btn-primary" })
            <a href="@Url.Action("ExportToExcel", "KHACHHANGs_63130803")" class="btn btn-primary">Xuất sang file excel</a>
        </div>
        <div class="card mb-4">
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Ảnh</th>
                            <th>Họ Tên</th>
                            <th>SĐT</th>
                            <th>Địa Chỉ</th>
                            <th>Ngày Sinh</th>
                            <th>Giới Tính</th>
                            <th>Email</th>
                            <th>Chức Năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td><img style="width: 70px; height: 70px;" src="~/Content/img/Avatar/@Html.DisplayFor(modelItem => item.anh)" alt="Avatar" /></td>
                                <td>@Html.DisplayFor(modelItem => item.hoTenKH)</td>
                                <td>@Html.DisplayFor(modelItem => item.SDT)</td>
                                <td>@Html.DisplayFor(modelItem => item.diaChi)</td>
                                <td>@Html.DisplayFor(modelItem => item.ngaySinh)</td>
                                <td>
                                    @{
                                        if (item.gioiTinh == true)
                                        {
                                            gtinh = "Nam";
                                        }
                                        else
                                        {
                                            gtinh = "Nữ";
                                        }
                                    }
                                    @gtinh
                                </td>
                                <td>@Html.DisplayFor(modelItem => item.email)</td>
                                <td>
                                    <div class="d-flex">
                                        <a href="@Url.Action("Edit", new { id = item.maKH })"><i class="fa-solid fa-lg fa-pen-to-square"></i></a>
                                        <div class="ms-2"></div>
                                        <a href="@Url.Action("Details", new { id = item.maKH })"><i class="fa-solid fa-lg fa-circle-info"></i></a>
                                        <div class="ms-2"></div>
                                        <a href="@Url.Action("Delete", new { id = item.maKH })"><i class="fa-regular fa-lg fa-trash-can"></i></a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>