QLVinpearl_63130803/Controllers/LoginKhachHang_63130803Controller.cs
using QLVinpearl_63130803.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLVinpearl_63130803.Controllers
{
    public class LoginKhachHang_63130803Controller : Controller
    {
        private QLVinpearl_63130803Entities db = new QLVinpearl_63130803Entities();
        // GET: LoginKhachHang_63130803
        public ActionResult Index()
        {
            return View();
        }
        private bool IsEmailExists(string email)
        {
            return db.KHACHHANGs.Any(kh => kh.email == email);
        }
        string LayMaKH()
        {
            // query lấy mã cuối cùng trong bảng và parse sang số
            var maMax = db.KHACHHANGs.ToList().Select(n => n.maKH).Max();
            int maKH = int.Parse(maMax.Substring(2)) + 1;
            // mã kh: KH000000 => 6 số
            string KH = maKH.ToString().PadLeft(6, '0');
            return "KH" + KH;
        }
        // GET: Customer/Register
        public ActionResult Register()
        {
            ViewBag.MaKH = LayMaKH();
            return View();
        }
		// POST: Customer/Register
		[HttpPost]
		public ActionResult Register(KHACHHANG model)
		{

			if (IsEmailExists(model.email))
			{
				ModelState.AddModelError("Email", "Email đã được sử dụng.");
				return View(model);
			}

			if (ModelState.IsValid)
			{
				Session["EmailKH"] = model.email;
				model.maKH = LayMaKH();
				db.KHACHHANGs.Add(model);
				db.SaveChanges();
				return RedirectToAction("Index", "DICHVU_63130803");
			}
			return View(model);
		}

		// GET: LoginKhachHang
		public ActionResult Login()
		{
			return View();
		}
		// POST: LoginKhachHang
		[HttpPost]
		public ActionResult Login(LoginKhachHangModel_63130803 model)
		{
			var user = db.KHACHHANGs.SingleOrDefault(kh => kh.email == model.Email);
			if (user == null)
			{
				ModelState.AddModelError("Email", "Tài khoản không tồn tại!");
			}
			else if (user.matKhau == model.MKhau)
			{
				Session["EmailKH"] = model.Email;
				return RedirectToAction("Index", "DICHVU_63130803");
			}
			else if (user.matKhau != model.MKhau)
			{
				ModelState.AddModelError("MKhau", "Mật khẩu không chính xác!");
			}
			else
			{
				ModelState.AddModelError("", "Thông tin tài khoản không hợp lệ!");
			}
			return View("Login");
		}

		public ActionResult Logout()
		{
			Session["EmailKH"] = null;
			return RedirectToAction("Index", "DICHVU_63130803");
		}
	}
}

QLVinpearl_63130803/Views/LoginKhachHang_63130803/Login.cshtml
@model QLVinpearl_63130803.Models.LoginKhachHangModel_63130803
@{
    ViewBag.Title = "Đăng Nhập";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="https://statics.vinpearl.com/favicon.png" type="image/png">
    <title>@ViewBag.Title - Vinpearl</title>
    <link href="~/Content/css/adminPageStyle.css" rel="stylesheet" />
    <link href="~/Content/css/detailUser.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"
            crossorigin="anonymous"></script>
</head>
<body>
    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Đăng Nhập</p>

                                    @using (Html.BeginForm("Login", "LoginKhachHang_63130803", FormMethod.Post, new { @class = "mx-1 mx-md-4" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="d-flex flex-row align-items-lg-end mb-4">
                                            <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <label class="form-label" for="form3Example3c">Email</label>
                                                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-lg-end mb-4">
                                            <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <label class="form-label" for="form3Example4c">Mật Khẩu</label>
                                                @Html.PasswordFor(model => model.MKhau, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.MKhau, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="d-flex flex-row justify-content-end mb-4">
                                            <a href="@Url.Action("SendMail","ResetPassword_63130803")" style="text-decoration: none; margin-left: 45%">Quên Mật Khẩu</a>
                                        </div>
                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                            <button type="submit" class="btn btn-primary btn-lg">Đăng Nhập</button>
                                        </div>
                                    }
                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                                         class="img-fluid" alt="Sample image">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

QLVinpearl_63130803/Views/LoginKhachHang_63130803/Register.cshtml
@model QLVinpearl_63130803.Models.KHACHHANG

@{
    ViewBag.Title = "Đăng Ký";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <link rel="shortcut icon" href="https://statics.vinpearl.com/favicon.png" type="image/png">
    <title>@ViewBag.Title - Vinpearl</title>
    <link href="~/Content/css/adminPageStyle.css" rel="stylesheet" />
    <link href="~/Content/css/detailUser.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"
            crossorigin="anonymous"></script>
</head>
<body>

    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Đăng Ký</p>

                                    @using (Html.BeginForm("Register", "LoginKhachHang_63130803", FormMethod.Post, new { @class = "mx-1 mx-md-4" }))
                                    {
                                        <div class="d-flex flex-row align-items-lg-end mb-4">
                                            <i class="fas fa-user fa-lg me-3 fa-fw"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <label class="form-label" for="form3Example1c">Họ Và Tên</label>
                                                @Html.TextBoxFor(model => model.hoTenKH, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.hoTenKH, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-lg-end mb-4">
                                            <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <label class="form-label" for="form3Example3c">Email</label>
                                                @Html.TextBoxFor(model => model.email, new { @class = "form-control" })
                                                @if (!string.IsNullOrEmpty(ViewData.ModelState["Email"]?.Errors.FirstOrDefault()?.ErrorMessage))
                                                {
                                                    <span class="text-danger">@ViewData.ModelState["Email"].Errors.FirstOrDefault().ErrorMessage</span>
                                                }
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-lg-end mb-4">
                                            <i class="fa-solid fa-phone fa-lg me-3 fa-fw"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <label class="form-label" for="form3Example4c">Số Điện Thoại</label>
                                                @Html.TextBoxFor(model => model.SDT, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="d-flex flex-row align-items-lg-end mb-4">
                                            <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                                            <div class="form-outline flex-fill mb-0">
                                                <label class="form-label" for="form3Example4c">Mật Khẩu</label>
                                                @Html.PasswordFor(model => model.matKhau, new { @class = "form-control" })
                                                @Html.ValidationMessageFor(model => model.matKhau, "", new { @class = "text-danger" })
                                            </div>
                                        </div>

                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                            <button type="submit" class="btn btn-primary btn-lg">Đăng Ký</button>
                                        </div>
                                    }
                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                                         class="img-fluid" alt="Sample image">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>