QLVinpearl_63130803/Areas/Admin/Controllers/SOCAs_63130803Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLVinpearl_63130803.Models;

namespace QLVinpearl_63130803.Areas.Admin.Controllers
{
    public class SOCAs_63130803Controller : Controller
    {
        private QLVinpearl_63130803Entities db = new QLVinpearl_63130803Entities();
        // Kiểm tra quyền của nhân viên
        public bool CheckPermission(string maChucNang)
        {
            if (Session["maLNV"] == null) Response.Redirect("~/Admin/Login_63130803/Index");
            var userSession = Session["maLNV"].ToString();
            var count = db.PHANQUYENs.Count(m => m.maLoaiNV == userSession && m.maChucNang == maChucNang);
            if (count == 0)
            {
                return false;
            }
            return true;
        }
        // GET: Admin/SOCAs_63130803
        public ActionResult Index()
        {
            if (CheckPermission("CN01") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            var sOCAs = db.SOCAs.Include(s => s.NHANVIEN);
            return View(sOCAs.ToList());
        }

        // GET: Admin/SOCAs_63130803/Details/5
        public ActionResult Details(string id)
        {
            if (CheckPermission("CN01") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOCA sOCA = db.SOCAs.Find(id);
            if (sOCA == null)
            {
                return HttpNotFound();
            }
            return View(sOCA);
        }

        // GET: Admin/SOCAs_63130803/Create
        public ActionResult Create()
        {
            if (CheckPermission("CN02") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            ViewBag.maNV = new SelectList(db.NHANVIENs, "maNV", "maLoaiNV");
            return View();
        }

        // POST: Admin/SOCAs_63130803/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "maCa,maNV,soCa1")] SOCA sOCA)
        {
            if (ModelState.IsValid)
            {
                db.SOCAs.Add(sOCA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.maNV = new SelectList(db.NHANVIENs, "maNV", "maLoaiNV", sOCA.maNV);
            return View(sOCA);
        }

        // GET: Admin/SOCAs_63130803/Edit/5
        public ActionResult Edit(string maCa, string maNV)
        {
            if (CheckPermission("CN03") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            if (maCa == null || maNV == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOCA sOCA = db.SOCAs.SingleOrDefault(x => x.maCa == maCa && x.maNV == maNV);
            if (sOCA == null)
            {
                return HttpNotFound();
            }
            ViewBag.maNV = new SelectList(db.NHANVIENs, "maNV", "maLoaiNV", sOCA.maNV);
            return View(sOCA);
        }

        // POST: Admin/SOCAs_63130803/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "maCa,maNV,soCa1")] SOCA sOCA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sOCA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.maNV = new SelectList(db.NHANVIENs, "maNV", "maLoaiNV", sOCA.maNV);
            return View(sOCA);
        }

        // GET: Admin/SOCAs_63130803/Delete/5
        public ActionResult Delete(string maCa, string maNV)
        {
            if (CheckPermission("CN04") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            if (maCa == null || maNV == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SOCA sOCA = db.SOCAs.SingleOrDefault(x => x.maCa == maCa && x.maNV == maNV);
            if (sOCA == null)
            {
                return HttpNotFound();
            }
            return View(sOCA);
        }

        // POST: Admin/SOCAs_63130803/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string maCa, string maNV)
        {
            SOCA sOCA = db.SOCAs.SingleOrDefault(x => x.maCa == maCa && x.maNV == maNV);
            if (sOCA == null)
            {
                return HttpNotFound();
            }
            db.SOCAs.Remove(sOCA);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLVinpearl_63130803/Areas/Admin/Views/SOCAs_63130803/Create.cshtml
@model QLVinpearl_63130803.Models.SOCA

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@using (Html.BeginForm("Edit", "SOCAs_63130803", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row justify-content-center align-items-center h-100">
                <div class="col-12 col-lg-9 col-xl-7">
                    <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                        <div class="card-body p-4 p-md-5">
                            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Thêm thông tin ca của nhân viên</h3>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        @Html.EditorFor(model => model.maCa, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.maCa, "", new { @class = "text-danger" })
                                        <label class="form-label fw-bold">Mã Ca</label>
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        @Html.EditorFor(model => model.maNV, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.maNV, "", new { @class = "text-danger" })
                                        <label class="form-label fw-bold">Mã Nhân Viên</label>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        @Html.EditorFor(model => model.soCa1, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.soCa1, "", new { @class = "text-danger" })
                                        <label class="form-label fw-bold">Số Ca</label>
                                    </div>
                                </div>
                            </div>
                            <div style="width: 100%; display: flex">
                                <div class="m-auto">
                                    <input class="btn btn-primary btn-lg" type="submit" value="Thêm" />
                                    @Html.ActionLink("Quay Về", "Index", null, new { @class = "btn btn-primary btn-lg" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

QLVinpearl_63130803/Areas/Admin/Views/SOCAs_63130803/Delete.cshtml
@model QLVinpearl_63130803.Models.SOCA

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="container">
    <br />
    <h3>Bạn có chắc chắn muốn xoá ca làm của nhân viên này không?</h3>
    <br />
    <p><span class="fw-bold">Mã ca</span><br /><span>@Html.DisplayFor(model => model.maCa)</span></p>
    <p><span class="fw-bold">Tên nhân viên</span><br /><span>@Html.DisplayFor(model => model.NHANVIEN.hoTenNV)</span></p>
    <p><span class="fw-bold">Số ca</span><br /><span>@Html.DisplayFor(model => model.soCa1)</span></p>
    @using (Html.BeginForm("Delete", "HOADONs_63130803", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.maCa)
        @Html.HiddenFor(model => model.maNV)
        <div class="m-auto">
            <input class="btn btn-primary btn-lg" type="submit" value="Xoá" />
            @Html.ActionLink("Quay Về", "Index", null, new { @class = "btn btn-primary btn-lg" })
        </div>
    }
</div>

QLVinpearl_63130803/Areas/Admin/Views/SOCAs_63130803/Details.cshtml
@model QLVinpearl_63130803.Models.SOCA

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>SOCA</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.soCa1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soCa1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NHANVIEN.maLoaiNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NHANVIEN.maLoaiNV)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QLVinpearl_63130803/Areas/Admin/Views/SOCAs_63130803/Edit.cshtml
@model QLVinpearl_63130803.Models.SOCA

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@using (Html.BeginForm("Edit", "SOCAs_63130803", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row justify-content-center align-items-center h-100">
                <div class="col-12 col-lg-9 col-xl-7">
                    <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                        <div class="card-body p-4 p-md-5">
                            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Sửa thông tin ca của nhân viên</h3>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.maCa)
                            @Html.HiddenFor(model => model.maNV)
                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        <label class="form-label fw-bold">Tên Nhân Viên</label>
                                        @Html.EditorFor(model => model.NHANVIEN.hoTenNV, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.NHANVIEN.hoTenNV, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        <label class="form-label fw-bold">Số Ca</label>
                                        @Html.EditorFor(model => model.soCa1, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.soCa1, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>
                            <div style="width: 100%">
                                <div class="m-auto">
                                    <input class="btn btn-primary btn-lg" type="submit" value="Sửa" />
                                    @Html.ActionLink("Quay Về", "Index", null, new { @class = "btn btn-primary btn-lg" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

QLVinpearl_63130803/Areas/Admin/Views/SOCAs_63130803/Index.cshtml
@model IEnumerable<QLVinpearl_63130803.Models.SOCA>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<main>
    <div class="container-fluid px-4">
        <div class="my-3">
            @Html.ActionLink("Thêm mới", "Create", null, new { @class = "btn btn-primary" })
        </div>
        <div class="card mb-4">
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Mã Ca</th>
                            <th>Mã Nhân Viên</th>
                            <th>Số Ca</th>
                            <th>Chức Năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.maCa)</td>
                                <th>@Html.DisplayFor(modelItem => item.maNV)</th>
                                <th>@Html.DisplayFor(modelItem => item.soCa1)</th>
                                <td>
                                    <div class="d-flex">
                                        <a href="@Url.Action("Edit", new { maCa = item.maCa, maNV = item.maNV })"><i class="fa-solid fa-lg fa-pen-to-square"></i></a>
                                        <div class="ms-2"></div>
                                        <a href="@Url.Action("Delete", new { maCa = item.maCa, maNV = item.maNV })"><i class="fa-regular fa-lg fa-trash-can"></i></a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>