QLVinpearl_63130803/Areas/Admin/Controllers/LOAIDICHVUs_63130803Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLVinpearl_63130803.Models;

namespace QLVinpearl_63130803.Areas.Admin.Controllers
{
    public class LOAIDICHVUs_63130803Controller : Controller
    {
        private QLVinpearl_63130803Entities db = new QLVinpearl_63130803Entities();
        // Kiểm tra quyền của nhân viên
        public bool CheckPermission(string maChucNang)
        {
            if (Session["maLNV"] == null) Response.Redirect("~/Admin/Login_63130803/Index");
            var userSession = Session["maLNV"].ToString();
            var count = db.PHANQUYENs.Count(m => m.maLoaiNV == userSession && m.maChucNang == maChucNang);
            if (count == 0)
            {
                return false;
            }
            return true;
        }
        // GET: Admin/LOAIDICHVUs_63130803
        public ActionResult Index()
        {
            if (CheckPermission("CN01") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            return View(db.LOAIDVs.ToList());
        }

        // GET: Admin/LOAIDICHVUs_63130803/Details/5
        public ActionResult Details(string id)
        {
            if (CheckPermission("CN01") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAIDV lOAIDV = db.LOAIDVs.Find(id);
            if (lOAIDV == null)
            {
                return HttpNotFound();
            }
            return View(lOAIDV);
        }

        // GET: Admin/LOAIDICHVUs_63130803/Create
        public ActionResult Create()
        {
            if (CheckPermission("CN02") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            return View();
        }

        // POST: Admin/LOAIDICHVUs_63130803/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "maLoaiDV,tenLoai")] LOAIDV lOAIDV)
        {
            if (ModelState.IsValid)
            {
                db.LOAIDVs.Add(lOAIDV);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(lOAIDV);
        }

        // GET: Admin/LOAIDICHVUs_63130803/Edit/5
        public ActionResult Edit(string id)
        {
            if (CheckPermission("CN03") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAIDV lOAIDV = db.LOAIDVs.Find(id);
            if (lOAIDV == null)
            {
                return HttpNotFound();
            }
            return View(lOAIDV);
        }

        // POST: Admin/LOAIDICHVUs_63130803/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "maLoaiDV,tenLoai")] LOAIDV lOAIDV)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lOAIDV).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(lOAIDV);
        }

        // GET: Admin/LOAIDICHVUs_63130803/Delete/5
        public ActionResult Delete(string id)
        {
            if (CheckPermission("CN04") == false)
            {
                Response.Redirect("~/Admin/PermissionError_63130803/NotAllowPermission");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LOAIDV lOAIDV = db.LOAIDVs.Find(id);
            if (lOAIDV == null)
            {
                return HttpNotFound();
            }
            return View(lOAIDV);
        }

        // POST: Admin/LOAIDICHVUs_63130803/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            LOAIDV lOAIDV = db.LOAIDVs.Find(id);
            db.LOAIDVs.Remove(lOAIDV);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLVinpearl_63130803/Areas/Admin/Views/LOAIDICHVUs_63130803/Create.cshtml
@model QLVinpearl_63130803.Models.LOAIDV

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@using (Html.BeginForm("Create", "LOAIDICHVUs_63130803", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row justify-content-center align-items-center h-100">
                <div class="col-12 col-lg-9 col-xl-7">
                    <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                        <div class="card-body p-4 p-md-5">
                            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Thêm mới loại dịch vụ</h3>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="row">
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        @Html.EditorFor(model => model.maLoaiDV, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.maLoaiDV, "", new { @class = "text-danger" })
                                        <label class="form-label fw-bold">Mã Loại Dịch Vụ</label>
                                    </div>
                                </div>
                                <div class="col-md-6 mb-4">
                                    <div class="form-outline">
                                        @Html.EditorFor(model => model.tenLoai, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.tenLoai, "", new { @class = "text-danger" })
                                        <label class="form-label fw-bold">Tên Loại Dịch Vụ</label>
                                    </div>
                                </div>
                            </div>

                            <div style="width: 100%; display: flex">
                                <div class="m-auto">
                                    <input class="btn btn-primary btn-lg" type="submit" value="Thêm" />
                                    @Html.ActionLink("Quay Về", "Index", null, new { @class = "btn btn-primary btn-lg" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

QLVinpearl_63130803/Areas/Admin/Views/LOAIDICHVUs_63130803/Delete.cshtml
@model QLVinpearl_63130803.Models.LOAIDV

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="container">
    <br />
    <h3>Bạn có chắc chắn muốn xoá loại dịch vụ này không?</h3>
    <br />
    <p><span class="fw-bold">Mã loại dịch vụ</span><br /><span>@Html.DisplayFor(model => model.maLoaiDV)</span></p>
    <p><span class="fw-bold">Tên loại dịch vụ</span><br /><span>@Html.DisplayFor(model => model.tenLoai)</span></p>
    @using (Html.BeginForm("Delete", "LOAIDICHVUs_63130803", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="m-auto">
            <input class="btn btn-primary btn-lg" type="submit" value="Xoá" />
            @Html.ActionLink("Quay Về", "Index", null, new { @class = "btn btn-primary btn-lg" })
        </div>
    }
</div>

QLVinpearl_63130803/Areas/Admin/Views/LOAIDICHVUs_63130803/Details.cshtml
@model QLVinpearl_63130803.Models.LOAIDV

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>LOAIDV</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tenLoai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.maLoaiDV }) |
    @Html.ActionLink("Back to List", "Index")
</p>

QLVinpearl_63130803/Areas/Admin/Views/LOAIDICHVUs_63130803/Edit.cshtml
@model QLVinpearl_63130803.Models.LOAIDV

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@using (Html.BeginForm("Edit", "LOAIDICHVUs_63130803", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row justify-content-center align-items-center h-100">
                <div class="col-12 col-lg-9 col-xl-7">
                    <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
                        <div class="card-body p-4 p-md-5">
                            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Sửa thông tin loại dịch vụ</h3>
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="row">
                                <div class="col-md-12 mb-4">
                                    <div class="form-outline">
                                        <label class="form-label fw-bold">Mã Loại Dịch Vụ</label>
                                        @Html.EditorFor(model => model.maLoaiDV, new { htmlAttributes = new { @class = "form-control form-control-lg", @readonly = "readonly" } })
                                        @Html.ValidationMessageFor(model => model.maLoaiDV, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12 mb-4">
                                    <div class="form-outline">
                                        <label class="form-label fw-bold">Tên Loại Dịch Vụ</label>
                                        @Html.EditorFor(model => model.tenLoai, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                        @Html.ValidationMessageFor(model => model.tenLoai, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div style="width: 100%">
                                <div class="m-auto">
                                    <input class="btn btn-primary btn-lg" type="submit" value="Thêm" />
                                    @Html.ActionLink("Quay Về", "Index", null, new { @class = "btn btn-primary btn-lg" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
}

QLVinpearl_63130803/Areas/Admin/Views/LOAIDICHVUs_63130803/Index.cshtml
@model IEnumerable<QLVinpearl_63130803.Models.LOAIDV>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<main>
    <div class="container-fluid px-4">
        <br />
        <h2>Danh sách loại dịch vụ</h2>

        <div class="my-3">
            @Html.ActionLink("Thêm mới", "Create", null, new { @class = "btn btn-primary" })
        </div>
        <div class="card mb-4">
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Mã Loại Dịch Vụ</th>
                            <th>Tên Loại Dịch Vụ</th>
                            <th>Chức Năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@Html.DisplayFor(modelItem => item.maLoaiDV)</td>
                                <th>@Html.DisplayFor(modelItem => item.tenLoai)</th>
                                <td>
                                    <div class="d-flex">
                                        <a href="@Url.Action("Edit", new { id = item.maLoaiDV })"><i class="fa-solid fa-lg fa-pen-to-square"></i></a>
                                        <div class="ms-2"></div>
                                        <a href="@Url.Action("Delete", new { id = item.maLoaiDV })"><i class="fa-regular fa-lg fa-trash-can"></i></a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>